import { ApiEndpointDefinition } from '@/types/api';

export const ALL_50_UKK_ENDPOINTS: ApiEndpointDefinition[] = [
  // 1. Root & Health Check Service
  {
    no: 1,
    method: 'GET',
    endpoint: '/',
    role: 'Publik',
    description: 'Status API & Petunjuk Penggunaan (Root Endpoint)',
    category: '1. Root & Health Check',
    hasAuth: false,
  },
  {
    no: 2,
    method: 'GET',
    endpoint: '/health',
    role: 'Publik',
    description: 'Health Check Server',
    category: '1. Root & Health Check',
    hasAuth: false,
  },

  // 2. Multi-Tenancy Siswa (App Maker)
  {
    no: 3,
    method: 'POST',
    endpoint: '/api/maker/register',
    role: 'Publik',
    description: 'Registrasi Akun Siswa (Mendapatkan App Key Unik)',
    category: '2. Multi-Tenancy App Maker',
    hasAuth: false,
    sampleBody: {
      name: 'Budi Santoso',
      username: 'budisantoso',
      email: 'budi@smk.sch.id',
      password: 'Password123!',
    },
  },
  {
    no: 4,
    method: 'POST',
    endpoint: '/api/maker/login',
    role: 'Publik',
    description: 'Login Akun Siswa Pengembang Frontend',
    category: '2. Multi-Tenancy App Maker',
    hasAuth: false,
    sampleBody: {
      usernameOrEmail: 'budisantoso',
      password: 'Password123!',
    },
  },
  {
    no: 5,
    method: 'GET',
    endpoint: '/api/maker/me',
    role: 'App Maker',
    description: 'Lihat Profil & App Key Siswa Saat Ini',
    category: '2. Multi-Tenancy App Maker',
    hasAuth: true,
  },
  {
    no: 6,
    method: 'GET',
    endpoint: '/api/maker/stats',
    role: 'App Maker',
    description: 'Statistik Keseluruhan Data Siswa (App Maker)',
    category: '2. Multi-Tenancy App Maker',
    hasAuth: true,
  },
  {
    no: 7,
    method: 'GET',
    endpoint: '/api/maker/list',
    role: 'Guru/Penguji',
    description: 'Daftar Semua Siswa / App Maker Terdaftar',
    category: '2. Multi-Tenancy App Maker',
    hasAuth: false,
  },

  // 3. Autentikasi Pengguna (Member & Admin Space)
  {
    no: 8,
    method: 'POST',
    endpoint: '/api/auth/register/member',
    role: 'Publik',
    description: 'Registrasi Akun Member / Pelanggan Baru',
    category: '3. Autentikasi Pengguna',
    hasAuth: false,
    sampleBody: {
      username: 'johndoe',
      password: 'Secret123!',
      nama_member: 'John Doe',
      instansi: 'Universitas Indonesia / PT Maju Mundur',
      alamat: 'Jl. Sudirman No. 123, Jakarta Selatan',
      telp: '081234567890',
      foto: 'member_john.jpg',
    },
  },
  {
    no: 9,
    method: 'POST',
    endpoint: '/api/auth/register/admin-space',
    role: 'Publik',
    description: 'Registrasi Pengelola Lokasi / Admin Coworking Space',
    category: '3. Autentikasi Pengguna',
    hasAuth: false,
    sampleBody: {
      username: 'admin_space1',
      password: 'Admin123!',
      nama_coworking: 'Moklet Hub Coworking',
      nama_pemilik: 'Ahmad Bidin',
      telp: '081298765432',
    },
  },
  {
    no: 10,
    method: 'POST',
    endpoint: '/api/auth/login',
    role: 'Publik',
    description: 'Login Akun User (Member atau Admin Space) Mengembalikan JWT Token',
    category: '3. Autentikasi Pengguna',
    hasAuth: false,
    sampleBody: {
      username: 'johndoe',
      password: 'Secret123!',
    },
  },
  {
    no: 11,
    method: 'GET',
    endpoint: '/api/auth/profile',
    role: 'Bearer User',
    description: 'Cek Profil & Hak Akses Pengguna yang Sedang Login',
    category: '3. Autentikasi Pengguna',
    hasAuth: true,
  },

  // 4. Space Coworking (Katalog & Ketersediaan)
  {
    no: 12,
    method: 'GET',
    endpoint: '/api/spaces/types',
    role: 'Publik/User',
    description: 'Daftar Tipe Space (Personal Desk, Meeting Room, Private Office)',
    category: '4. Katalog & Ketersediaan Ruang',
    hasAuth: false,
  },
  {
    no: 13,
    method: 'GET',
    endpoint: '/api/spaces/availability',
    role: 'Publik/User',
    description: 'Cek Ketersediaan Space Berdasarkan Tanggal & Jam',
    category: '4. Katalog & Ketersediaan Ruang',
    hasAuth: false,
    sampleParams: '?id_space=1&tanggal=2026-08-30&jam_mulai=09:00&durasi_jam=3',
  },
  {
    no: 14,
    method: 'GET',
    endpoint: '/api/spaces',
    role: 'Publik/User',
    description: 'Lihat Semua Space Coworking (Filter ?tipe & ?search)',
    category: '4. Katalog & Ketersediaan Ruang',
    hasAuth: false,
    sampleParams: '?tipe=desk&search=Alpha',
  },
  {
    no: 15,
    method: 'GET',
    endpoint: '/api/spaces/{id}',
    role: 'Publik/User',
    description: 'Lihat Detail Space Coworking Berdasarkan ID',
    category: '4. Katalog & Ketersediaan Ruang',
    hasAuth: false,
    sampleParams: '/1',
  },

  // 5. Diskon & Promo (Katalog Diskon)
  {
    no: 16,
    method: 'GET',
    endpoint: '/api/diskon/active',
    role: 'Publik/User',
    description: 'Daftar Promo / Diskon yang Sedang Aktif',
    category: '5. Diskon & Promo',
    hasAuth: false,
  },
  {
    no: 17,
    method: 'POST',
    endpoint: '/api/diskon/check',
    role: 'Publik/User',
    description: 'Periksa Validitas & Hitung Potongan Kode Promo',
    category: '5. Diskon & Promo',
    hasAuth: false,
    sampleBody: {
      nama_diskon: 'DISKONHEMAT20',
    },
  },
  {
    no: 18,
    method: 'GET',
    endpoint: '/api/diskon/{id}',
    role: 'Publik/User',
    description: 'Lihat Detail Diskon Berdasarkan ID',
    category: '5. Diskon & Promo',
    hasAuth: false,
    sampleParams: '/1',
  },

  // 6. Reservasi Member (Pemesanan & Histori)
  {
    no: 19,
    method: 'POST',
    endpoint: '/api/reservasi',
    role: 'Member',
    description: 'Buat Pemesanan Space Baru (+ Kode Promo & Perhitungan Otomatis)',
    category: '6. Reservasi Member',
    hasAuth: true,
    sampleBody: {
      id_space: 1,
      tanggal_reservasi: '2026-08-30',
      jam_mulai: '09:00',
      durasi_jam: 3,
      id_diskon: 1,
      kode_promo: 'DISKONHEMAT20',
    },
  },
  {
    no: 20,
    method: 'GET',
    endpoint: '/api/reservasi/my',
    role: 'Member',
    description: 'Lihat Status Semua Pemesanan Milik Sendiri',
    category: '6. Reservasi Member',
    hasAuth: true,
  },
  {
    no: 21,
    method: 'GET',
    endpoint: '/api/reservasi/my/history',
    role: 'Member',
    description: 'Lihat Histori Pemesanan Berdasarkan Bulan & Tahun',
    category: '6. Reservasi Member',
    hasAuth: true,
    sampleParams: '?month=8&year=2026',
  },
  {
    no: 22,
    method: 'GET',
    endpoint: '/api/reservasi/{id}/e-ticket',
    role: 'Member/Admin',
    description: 'Cetak E-Ticket / Bukti Nota Digital Reservasi',
    category: '6. Reservasi Member',
    hasAuth: true,
    sampleParams: '/12/e-ticket',
  },
  {
    no: 23,
    method: 'GET',
    endpoint: '/api/reservasi/{id}',
    role: 'Member/Admin',
    description: 'Lihat Detail Reservasi Berdasarkan ID',
    category: '6. Reservasi Member',
    hasAuth: true,
    sampleParams: '/12',
  },
  {
    no: 24,
    method: 'PATCH',
    endpoint: '/api/reservasi/{id}/cancel',
    role: 'Member',
    description: 'Batalkan Pemesanan Space',
    category: '6. Reservasi Member',
    hasAuth: true,
    sampleParams: '/12/cancel',
  },

  // 7. Profil Lokasi Coworking Space (Panel Admin)
  {
    no: 25,
    method: 'GET',
    endpoint: '/api/admin/profile',
    role: 'Admin Space',
    description: 'Lihat Data Profil Lokasi Coworking Space',
    category: '7. Profil Coworking Admin',
    hasAuth: true,
  },
  {
    no: 26,
    method: 'PUT',
    endpoint: '/api/admin/profile',
    role: 'Admin Space',
    description: 'Update Data Profil Lokasi Coworking Space',
    category: '7. Profil Coworking Admin',
    hasAuth: true,
    sampleBody: {
      nama_coworking: 'Moklet Hub Coworking Space (Updated)',
      nama_pemilik: 'Ahmad Bidin, S.Kom',
      telp: '081298765432',
    },
  },

  // 8. Manajemen Member / Pelanggan (Panel Admin)
  {
    no: 27,
    method: 'GET',
    endpoint: '/api/admin/members',
    role: 'Admin Space',
    description: 'Daftar Semua Member / Pelanggan Coworking',
    category: '8. Manajemen Member Admin',
    hasAuth: true,
    sampleParams: '?search=Budi',
  },
  {
    no: 28,
    method: 'POST',
    endpoint: '/api/admin/members',
    role: 'Admin Space',
    description: 'Tambah Data Member Baru oleh Admin (Upload Foto)',
    category: '8. Manajemen Member Admin',
    hasAuth: true,
    sampleBody: {
      username: 'user_budi',
      password: 'Secret123!',
      nama_member: 'Budi Raharjo',
      instansi: 'SMK Telkom Malang',
      alamat: 'Jl. Danau Ranau No. 1, Sawojajar, Malang',
      telp: '085712345678',
      foto: 'budi.jpg',
    },
  },
  {
    no: 29,
    method: 'GET',
    endpoint: '/api/admin/members/{id}',
    role: 'Admin Space',
    description: 'Detail Data Member Berdasarkan ID',
    category: '8. Manajemen Member Admin',
    hasAuth: true,
    sampleParams: '/6',
  },
  {
    no: 30,
    method: 'PUT',
    endpoint: '/api/admin/members/{id}',
    role: 'Admin Space',
    description: 'Update Data Member / Pelanggan',
    category: '8. Manajemen Member Admin',
    hasAuth: true,
    sampleParams: '/6',
    sampleBody: {
      nama_member: 'John Doe, S.Kom',
      instansi: 'PT Inovasi Digital',
      alamat: 'Jl. Gatot Subroto No. 45, Jakarta',
      telp: '081234567890',
    },
  },
  {
    no: 31,
    method: 'DELETE',
    endpoint: '/api/admin/members/{id}',
    role: 'Admin Space',
    description: 'Hapus Data Member / Pelanggan',
    category: '8. Manajemen Member Admin',
    hasAuth: true,
    sampleParams: '/6',
  },

  // 9. Manajemen Space Ruangan & Meja (Panel Admin)
  {
    no: 32,
    method: 'GET',
    endpoint: '/api/admin/spaces',
    role: 'Admin Space',
    description: 'Daftar Semua Ruangan & Meja Milik Admin',
    category: '9. Manajemen Space Admin',
    hasAuth: true,
  },
  {
    no: 33,
    method: 'POST',
    endpoint: '/api/admin/spaces',
    role: 'Admin Space',
    description: 'Tambah Ruangan / Meja Space Baru Beserta Fasilitas & Foto',
    category: '9. Manajemen Space Admin',
    hasAuth: true,
    sampleBody: {
      nama_space: 'Personal Desk Alpha 01',
      harga_per_jam: 25000,
      tipe: 'desk',
      kapasitas: 1,
      deskripsi: 'Dilengkapi colokan listrik, WiFi 100Mbps, monitor 24 inch, dan free flow kopi/teh.',
      foto: 'desk_alpha_01.jpg',
    },
  },
  {
    no: 34,
    method: 'GET',
    endpoint: '/api/admin/spaces/{id}',
    role: 'Admin Space',
    description: 'Detail Data Space Berdasarkan ID',
    category: '9. Manajemen Space Admin',
    hasAuth: true,
    sampleParams: '/5',
  },
  {
    no: 35,
    method: 'PUT',
    endpoint: '/api/admin/spaces/{id}',
    role: 'Admin Space',
    description: 'Update Data Ruangan & Fasilitas Space',
    category: '9. Manajemen Space Admin',
    hasAuth: true,
    sampleParams: '/5',
    sampleBody: {
      nama_space: 'Personal Desk Alpha 01 (Updated)',
      harga_per_jam: 30000,
      tipe: 'desk',
      kapasitas: 2,
      deskripsi: 'Fasilitas terupdate dengan monitor 27 inch 4K dan standing desk elektrik.',
    },
  },
  {
    no: 36,
    method: 'DELETE',
    endpoint: '/api/admin/spaces/{id}',
    role: 'Admin Space',
    description: 'Hapus Data Ruangan / Meja Space',
    category: '9. Manajemen Space Admin',
    hasAuth: true,
    sampleParams: '/5',
  },

  // 10. Manajemen Kode Promo & Diskon (Panel Admin)
  {
    no: 37,
    method: 'GET',
    endpoint: '/api/admin/diskon',
    role: 'Admin Space',
    description: 'Daftar Semua Kode Promo / Diskon Event',
    category: '10. Manajemen Promo Admin',
    hasAuth: true,
  },
  {
    no: 38,
    method: 'POST',
    endpoint: '/api/admin/diskon',
    role: 'Admin Space',
    description: 'Tambah Kode Promo / Event Diskon Baru',
    category: '10. Manajemen Promo Admin',
    hasAuth: true,
    sampleBody: {
      nama_diskon: 'PROMOAGUSTUS',
      persentase_diskon: 20,
      tanggal_awal: '2026-08-01T00:00:00Z',
      tanggal_akhir: '2026-08-31T23:59:59Z',
    },
  },
  {
    no: 39,
    method: 'GET',
    endpoint: '/api/admin/diskon/{id}',
    role: 'Admin Space',
    description: 'Detail Data Diskon Berdasarkan ID',
    category: '10. Manajemen Promo Admin',
    hasAuth: true,
    sampleParams: '/4',
  },
  {
    no: 40,
    method: 'PUT',
    endpoint: '/api/admin/diskon/{id}',
    role: 'Admin Space',
    description: 'Update Data Kode Promo & Periode Diskon',
    category: '10. Manajemen Promo Admin',
    hasAuth: true,
    sampleParams: '/4',
    sampleBody: {
      nama_diskon: 'PROMOAGUSTUS2026',
      persentase_diskon: 25,
      tanggal_akhir: '2026-09-15T23:59:59Z',
    },
  },
  {
    no: 41,
    method: 'DELETE',
    endpoint: '/api/admin/diskon/{id}',
    role: 'Admin Space',
    description: 'Hapus Kode Promo / Diskon',
    category: '10. Manajemen Promo Admin',
    hasAuth: true,
    sampleParams: '/4',
  },

  // 11. Transaksi Reservasi & Check-In/Check-Out (Panel Admin)
  {
    no: 42,
    method: 'GET',
    endpoint: '/api/admin/reservasi',
    role: 'Admin Space',
    description: 'Lihat Seluruh Reservasi Coworking (?month, ?year, ?status, ?id_space, ?tanggal)',
    category: '11. Operasional Reservasi Admin',
    hasAuth: true,
    sampleParams: '?month=8&year=2026&status=belum_dikonfirm',
  },
  {
    no: 43,
    method: 'PATCH',
    endpoint: '/api/admin/reservasi/{id}/status',
    role: 'Admin Space',
    description: 'Konfirmasi & Ubah Status Pemesanan (disetujui, dibatalkan, dll)',
    category: '11. Operasional Reservasi Admin',
    hasAuth: true,
    sampleParams: '/12/status',
    sampleBody: {
      status: 'disetujui',
    },
  },
  {
    no: 44,
    method: 'POST',
    endpoint: '/api/admin/reservasi/{id}/check-in',
    role: 'Admin Space',
    description: 'Check-In Pelanggan (Status Berubah ke Aktif/Digunakan)',
    category: '11. Operasional Reservasi Admin',
    hasAuth: true,
    sampleParams: '/12/check-in',
  },
  {
    no: 45,
    method: 'POST',
    endpoint: '/api/admin/reservasi/{id}/check-out',
    role: 'Admin Space',
    description: 'Check-Out Pelanggan (Status Berubah ke Selesai)',
    category: '11. Operasional Reservasi Admin',
    hasAuth: true,
    sampleParams: '/12/check-out',
  },

  // 12. Rekapitulasi Laporan Pendapatan Bulanan (Panel Admin)
  {
    no: 46,
    method: 'GET',
    endpoint: '/api/admin/reports/monthly',
    role: 'Admin Space',
    description: 'Rekapitulasi Estimasi & Realisasi Pendapatan Per Bulan (?month, ?year)',
    category: '12. Laporan Finansial Admin',
    hasAuth: true,
    sampleParams: '?month=8&year=2026',
  },
  {
    no: 47,
    method: 'GET',
    endpoint: '/api/admin/reports/income',
    role: 'Admin Space',
    description: 'Alias Endpoint untuk Rekapitulasi Pendapatan Bulanan (?month, ?year)',
    category: '12. Laporan Finansial Admin',
    hasAuth: true,
    sampleParams: '?month=8&year=2026',
  },

  // 13. Upload Berkas & Gambar (Media)
  {
    no: 48,
    method: 'POST',
    endpoint: '/api/upload/image',
    role: 'User/Admin',
    description: 'Upload Berkas Gambar Umum (Multipart Form Data)',
    category: '13. Upload Berkas & Media',
    hasAuth: true,
  },
  {
    no: 49,
    method: 'POST',
    endpoint: '/api/upload/spaces',
    role: 'Admin Space',
    description: 'Upload Foto Ruangan / Meja Space (Multipart Form Data)',
    category: '13. Upload Berkas & Media',
    hasAuth: true,
  },
  {
    no: 50,
    method: 'POST',
    endpoint: '/api/upload/members',
    role: 'User/Admin',
    description: 'Upload Foto Profil Member / Pelanggan (Multipart Form Data)',
    category: '13. Upload Berkas & Media',
    hasAuth: true,
  },
];
