import { Space, Discount, Reservation, Member, AdminProfile, MonthlyReport, IncomeReport } from '@/types/api';

export const INITIAL_SPACES: Space[] = [
  {
    id_space: 1,
    nama_space: 'Atelier Focus Desk A-01',
    tipe: 'desk',
    harga_per_jam: 25000,
    kapasitas: 1,
    deskripsi: 'Workstation ergonomis dengan pencahayaan alami, kursi Herman Miller Aeron, dual power sockets, monitor Dell UltraSharp 27" 4K, dan akses high-speed optical fiber 300 Mbps.',
    foto: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    tersedia: true,
    fasilitas: ['Kursi Ergonomis', 'Monitor 4K 27"', 'High-Speed WiFi', 'Free Flow Coffee/Tea', 'Power Hub'],
  },
  {
    id_space: 2,
    nama_space: 'Minimalist Focus Desk B-04',
    tipe: 'desk',
    harga_per_jam: 20000,
    kapasitas: 1,
    deskripsi: 'Meja kerja individual di zona silent study. Cocok untuk programmer, desainer, dan pelajar yang memerlukan konsentrasi tinggi bebas distraksi suara.',
    foto: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1200&q=80',
    tersedia: true,
    fasilitas: ['Quiet Zone', 'Power Outlet', 'Ethernet Port', 'Ergonomic Chair', 'Locker Pribadi'],
  },
  {
    id_space: 3,
    nama_space: 'Nordic Boardroom Executive',
    tipe: 'meeting_room',
    harga_per_jam: 150000,
    kapasitas: 12,
    deskripsi: 'Ruang rapat eksekutif bergaya arsitektur Skandinavia. Dilengkapi smart display interactive 75", video conference PTZ camera, audio echo cancellation, dan white glassboard.',
    foto: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=1200&q=80',
    tersedia: true,
    fasilitas: ['Smart TV 75" 4K', 'Conference Camera PTZ', 'Boundary Mic', 'Glass Whiteboard', 'Wireless Presentation'],
  },
  {
    id_space: 4,
    nama_space: 'Creative Studio Meeting Room',
    tipe: 'meeting_room',
    harga_per_jam: 85000,
    kapasitas: 6,
    deskripsi: 'Ruang diskusi kreatif berkapasitas sedang. Sangat ideal untuk sesi brainstorming tim, presentasi pitching klien, maupun ujian lisan projek kolaboratif.',
    foto: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1200&q=80',
    tersedia: true,
    fasilitas: ['4K Display 55"', 'Acoustic Wall Panels', 'High-Speed WiFi', 'Flipchart & Marker', 'Air Conditioner'],
  },
  {
    id_space: 5,
    nama_space: 'Private Office Studio - Zenith Suite',
    tipe: 'private_office',
    harga_per_jam: 120000,
    kapasitas: 4,
    deskripsi: 'Kantor privat mandiri dengan akses keycard digital, privasi kaca soundproof double-glazed, lemari arsip terkunci, dan AC mandiri untuk tim startup atau studio riset.',
    foto: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    tersedia: true,
    fasilitas: ['Akses Kartu Digital RFID', 'Soundproof Glass', 'Dedicated Router', 'Whiteboard', 'Storage Cabinet'],
  },
  {
    id_space: 6,
    nama_space: 'Penthouse Private Suite - Apex',
    tipe: 'private_office',
    harga_per_jam: 200000,
    kapasitas: 8,
    deskripsi: 'Ruang kerja privat premium dengan pemandangan lanskap kota. Dilengkapi sofa lounge mini, mini bar refreshment, dan meja kerja kayu oak solid.',
    foto: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
    tersedia: true,
    fasilitas: ['Lounge Sofa', 'City Panoramic View', 'Executive Desk', 'Private Coffee Bar', 'Full Soundproofing'],
  },
];

export const INITIAL_DISCOUNTS: Discount[] = [
  {
    id_diskon: 1,
    nama_diskon: 'DISKONHEMAT20',
    persentase_diskon: 20,
    tanggal_awal: '2026-01-01',
    tanggal_akhir: '2026-12-31',
    is_active: true,
  },
  {
    id_diskon: 2,
    nama_diskon: 'SMKTELKOM30',
    persentase_diskon: 30,
    tanggal_awal: '2026-01-01',
    tanggal_akhir: '2026-12-31',
    is_active: true,
  },
  {
    id_diskon: 3,
    nama_diskon: 'MAHASISWA15',
    persentase_diskon: 15,
    tanggal_awal: '2026-01-01',
    tanggal_akhir: '2026-12-31',
    is_active: true,
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id_member: 101,
    username: 'ahmad_fauzi',
    nama_member: 'Ahmad Fauzi',
    instansi: 'SMK Telkom Malang (RPL)',
    alamat: 'Jl. Danau Ranau G7 B-12, Sawojajar, Malang',
    telp: '081234567890',
    foto: '',
    created_at: '2026-02-10',
  },
  {
    id_member: 102,
    username: 'sarah_nadira',
    nama_member: 'Sarah Nadira Putri',
    instansi: 'Universitas Brawijaya',
    alamat: 'Jl. Veteran No. 18, Malang',
    telp: '085712348901',
    foto: '',
    created_at: '2026-02-15',
  },
  {
    id_member: 103,
    username: 'budi_santoso',
    nama_member: 'Budi Santoso',
    instansi: 'Nusantara Digital Studio',
    alamat: 'Jl. Soekarno Hatta No. 45, Malang',
    telp: '082198765432',
    foto: '',
    created_at: '2026-03-01',
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id_reservasi: 1001,
    id_member: 101,
    nama_member: 'Ahmad Fauzi',
    id_space: 1,
    nama_space: 'Atelier Focus Desk A-01',
    tipe_space: 'desk',
    foto_space: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    harga_per_jam: 25000,
    tanggal_reservasi: '2026-09-15',
    jam_mulai: '09:00',
    durasi_jam: 4,
    id_diskon: 1,
    kode_promo: 'DISKONHEMAT20',
    persentase_diskon: 20,
    total_harga: 80000,
    status: 'aktif',
    waktu_check_in: '2026-09-15 08:55',
    waktu_check_out: null,
    created_at: '2026-09-14 14:20',
  },
  {
    id_reservasi: 1002,
    id_member: 102,
    nama_member: 'Sarah Nadira Putri',
    id_space: 3,
    nama_space: 'Nordic Boardroom Executive',
    tipe_space: 'meeting_room',
    foto_space: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=1200&q=80',
    harga_per_jam: 150000,
    tanggal_reservasi: '2026-09-16',
    jam_mulai: '13:00',
    durasi_jam: 3,
    id_diskon: 2,
    kode_promo: 'SMKTELKOM30',
    persentase_diskon: 30,
    total_harga: 315000,
    status: 'disetujui',
    waktu_check_in: null,
    waktu_check_out: null,
    created_at: '2026-09-14 18:45',
  },
  {
    id_reservasi: 1003,
    id_member: 103,
    nama_member: 'Budi Santoso',
    id_space: 5,
    nama_space: 'Private Office Studio - Zenith Suite',
    tipe_space: 'private_office',
    foto_space: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    harga_per_jam: 120000,
    tanggal_reservasi: '2026-09-17',
    jam_mulai: '10:00',
    durasi_jam: 5,
    id_diskon: null,
    kode_promo: null,
    persentase_diskon: 0,
    total_harga: 600000,
    status: 'belum_dikonfirm',
    waktu_check_in: null,
    waktu_check_out: null,
    created_at: '2026-09-15 07:10',
  },
  {
    id_reservasi: 1004,
    id_member: 101,
    nama_member: 'Ahmad Fauzi',
    id_space: 4,
    nama_space: 'Creative Studio Meeting Room',
    tipe_space: 'meeting_room',
    foto_space: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1200&q=80',
    harga_per_jam: 85000,
    tanggal_reservasi: '2026-09-10',
    jam_mulai: '14:00',
    durasi_jam: 2,
    id_diskon: 1,
    kode_promo: 'DISKONHEMAT20',
    persentase_diskon: 20,
    total_harga: 136000,
    status: 'selesai',
    waktu_check_in: '2026-09-10 13:58',
    waktu_check_out: '2026-09-10 16:02',
    created_at: '2026-09-09 11:30',
  },
  {
    id_reservasi: 1005,
    id_member: 102,
    nama_member: 'Sarah Nadira Putri',
    id_space: 2,
    nama_space: 'Minimalist Focus Desk B-04',
    tipe_space: 'desk',
    foto_space: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1200&q=80',
    harga_per_jam: 20000,
    tanggal_reservasi: '2026-09-08',
    jam_mulai: '10:00',
    durasi_jam: 3,
    id_diskon: null,
    kode_promo: null,
    persentase_diskon: 0,
    total_harga: 60000,
    status: 'dibatalkan',
    waktu_check_in: null,
    waktu_check_out: null,
    created_at: '2026-09-07 16:20',
  },
];

export const INITIAL_ADMIN_PROFILE: AdminProfile = {
  id_admin: 1,
  username: 'admin_thehive',
  nama_coworking: 'The Hive Sanctuary Coworking',
  nama_pemilik: 'Drs. Hendra Wibisono, M.T.',
  alamat: 'Jl. Danau Ranau No. 1, Sawojajar, Kota Malang, Jawa Timur 65139',
  telp: '0341-712345 / 0811-3456-789',
  deskripsi_fasilitas:
    'Fasilitas coworking modern terlengkap di Kota Malang dengan konsep Luxury Monochrome. Dilengkapi internet fiber optik simetris 1 Gbps, generator backup daya 100%, smart keycard access, ergonomic workstation by Herman Miller, soundproof phone booths, audio-visual conference room, dan specialty coffee brew bar gratis untuk seluruh member.',
};

export const INITIAL_MONTHLY_REPORT: MonthlyReport = {
  bulan: 'September',
  tahun: 2026,
  total_reservasi: 42,
  total_pendapatan: 14850000,
  reservasi_selesai: 34,
  reservasi_batal: 2,
  breakdown_status: {
    belum_dikonfirm: 1,
    disetujui: 3,
    aktif: 2,
    selesai: 34,
    dibatalkan: 2,
  },
};

export const INITIAL_INCOME_REPORT: IncomeReport = {
  total_pendapatan: 14850000,
  distribusi_tipe: [
    {
      tipe: 'desk',
      label: 'Personal Desk',
      total_reservasi: 24,
      total_pendapatan: 3840000,
      persentase: 26,
    },
    {
      tipe: 'meeting_room',
      label: 'Meeting Room',
      total_reservasi: 12,
      total_pendapatan: 5410000,
      persentase: 36,
    },
    {
      tipe: 'private_office',
      label: 'Private Office',
      total_reservasi: 6,
      total_pendapatan: 5600000,
      persentase: 38,
    },
  ],
  tren_bulanan: [
    { bulan: 'Mei', pendapatan: 9400000, reservasi: 28 },
    { bulan: 'Jun', pendapatan: 11200000, reservasi: 32 },
    { bulan: 'Jul', pendapatan: 12800000, reservasi: 37 },
    { bulan: 'Agu', pendapatan: 13950000, reservasi: 40 },
    { bulan: 'Sep', pendapatan: 14850000, reservasi: 42 },
  ],
};
